import {PHASES,CROPS,ITEMS,RESEARCH,RECIPES,PEOPLE,PROJECTS,STORY} from './data.js';
import * as E from './engine.js';
import {World} from './world.js';
import {applyIcons} from './icons.js';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state=E.loadGame(localStorage),tool='hand',panelMode=null,phaseView=state.phase,personId=null,dialogueIndex=0,route=[],pending=null,last=0,accum=0,saveAccum=0,audioContext=null,toastTimer;
const canvas=$('#world'),world=new World(canvas,state),panel=$('#panel');
applyIcons();
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function notify(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),4300);}
function save(){const ok=E.saveGame(state,localStorage);$('#save-status').textContent=ok?'Saved on this device':'Storage full · export your save';return ok;}
function sound(kind='work'){
  if(!state.sound)return;
  try{audioContext??=new (window.AudioContext||window.webkitAudioContext)();if(audioContext.state==='suspended')audioContext.resume();const now=audioContext.currentTime;const notes=kind==='success'?[392,494,587]:kind==='harvest'?[523,659]:[294];notes.forEach((f,i)=>{const o=audioContext.createOscillator(),g=audioContext.createGain();o.type='sine';o.frequency.value=f;g.gain.setValueAtTime(0,now+i*.08);g.gain.linearRampToValueAtTime(.055,now+i*.08+.01);g.gain.exponentialRampToValueAtTime(.001,now+i*.08+.25);o.connect(g);g.connect(audioContext.destination);o.start(now+i*.08);o.stop(now+i*.08+.27);});}catch{}
}
function result(r,{refresh=true}={}){notify(r.message);if(r.ok){sound(r.story?'success':'work');save();updateHUD();if(refresh&&panel.open)renderPanel();}return r;}
function sprite(index,large=false,atlas='people-crops'){return `<div class="sprite-window${large?' large':''}"><canvas data-sprite="${index}" data-atlas="${atlas}" width="200" height="200" aria-hidden="true"></canvas></div>`;}
function paintSprites(){for(const cv of $$('[data-sprite]')){const index=+cv.dataset.sprite,atlas=cv.dataset.atlas,im=world.images[atlas];if(!im)continue;const rows=atlas==='people-crops'?[0,324,634,934,1254]:[0,313.5,627,940.5,1254],row=Math.floor(index/4);cv.getContext('2d').drawImage(im,index%4*313.5,rows[row],313.5,rows[row+1]-rows[row],0,0,200,200);}}
const cost=(items,mult=1)=>`<div class="cost">${Object.entries(items).map(([id,n])=>`<span class="resource ${E.count(state,id)>=n*mult?'enough':'missing'}" title="${esc(ITEMS[id].name)}">${ITEMS[id].icon} ${esc(ITEMS[id].name)} ${E.count(state,id)}/${n*mult}</span>`).join('')}</div>`;
function updateHUD(){
  $('#coins b').textContent=state.coins.toLocaleString();$('#energy').textContent=Math.floor(state.energy);const days=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];$('#day').textContent=`Day ${state.day} · ${days[(state.day-1)%7]}`;
  const minutes=Math.floor(480+state.time/DAY()*840),h=Math.floor(minutes/60),m=Math.floor(minutes%60/10)*10;$('#time').textContent=`${h%12||12}:${String(m).padStart(2,'0')} ${h>=12?'PM':'AM'} · ${state.phase===3?'Familiar weather':'Early summer'}`;$('#weather').textContent=h>=18?'☾':'☀';
  $$('.places button').forEach(b=>b.classList.toggle('active',b.dataset.place===state.place));
  const names={farm:['The old Wren farm','Yours, mud and all.'],town:['Bumpkin Town',state.phase===1?'Six neighbours. Plenty of opinions.':state.phase===2?'A few things have started to hum.':'The ordinary has become quite particular.'],cellar:['Downstairs, something is humming',state.jobs.length?`${state.jobs.length} machine${state.jobs.length===1?'':'s'} at work.`:'Please mind the gourd bellows.']};
  $('#location-title').textContent=names[state.place][0];$('#location-subtitle').textContent=names[state.place][1];
  $('#chapter-label').textContent=`CHAPTER ${['ONE','TWO','THREE'][state.phase-1]} · ${PHASES[state.phase-1].toUpperCase()}`;
  let q;
  if(state.stats.cleared<3)q=['A little room to grow','Clear some brambles. There’s a farm in here somewhere.',`${state.stats.cleared} / 3 patches cleared`];
  else if(state.stats.harvested<12)q=['Something from the soil','Harvest the golden cogsquash. Save a little for Jun.',`${Math.min(12,state.stats.harvested)} / 12 crops harvested`];
  else if(state.stats.planted<6)q=['Put down some roots','Till, plant, and water six beds. Wirereed likes the creek.',`${Math.min(6,state.stats.planted)} / 6 seeds planted`];
  else{const next=RESEARCH.find(r=>r.phase===state.phase&&!E.has(state,r.id)&&r.requires.every(id=>E.has(state,id)));const g=E.gate(state);q=state.ending?['A town, still growing','There will always be another thing to mend.','The story is complete · keep tending']:next?[next.name,next.desc,`${g.research} / ${g.researchTotal} inventions · ${g.projects} / 3 town projects`]:g.ready?['A new patch in the quilt','Gather your neighbours and turn the page.','Chapter complete · open the almanac']:['Take it into town','Complete the three shared projects in the almanac.',`${g.projects} / 3 town projects`];}
  $('#quest-title').textContent=q[0];$('#quest-text').textContent=q[1];$('#quest-progress').textContent=q[2];
}
const DAY=()=>E.DAY_SECONDS;
function setTool(next,choose=true){tool=next;$$('[data-tool]').forEach(b=>b.classList.toggle('selected',b.dataset.tool===tool));if(tool==='seed'&&choose)openPanel('seeds');else{const hints={hand:'Tap a building, neighbour, or patch to explore.',clear:'Tap a tree, rock, or bramble to clear it.',hoe:'Tap an empty stitched bed to till it.',seed:`Planting ${CROPS[state.selectedSeed].name}. Tap an empty tilled bed.`,water:'Tap a planted bed. Your can never runs dry.',harvest:'Tap a crop with a golden sparkle.'};notify(hints[tool]);}}
function travel(place){route=[];pending=null;E.travel(state,place);world.state=state;world.recenter(true);closePanel();updateHUD();save();}
function header(title,subtitle='',eyebrow='THE BUMPKIN ALMANAC'){return `<div class="panel-head"><div><span class="eyebrow">${esc(eyebrow)}</span><h1>${esc(title)}</h1>${subtitle?`<p>${esc(subtitle)}</p>`:''}</div><button class="close" data-action="close" aria-label="Close panel">×</button></div>`;}
function tabs(active){return `<nav class="panel-tabs" aria-label="Almanac sections">${[['research','Research'],['workshop','Machines'],['projects','Town projects'],['people','Neighbours'],['notes','Field notes'],['help','How to play']].map(([id,n])=>`<button data-open="${id}" class="${active===id?'active':''}">${n}</button>`).join('')}</nav>`;}
function openPanel(mode){panelMode=mode;if(mode==='research')phaseView=state.phase;route=[];pending=null;renderPanel();if(!panel.open)panel.showModal();}
function closePanel(){panel.close();panelMode=null;canvas.focus({preventScroll:true});}
function renderPanel(){
  const scroll=panel.scrollTop;let content='';
  if(['research','workshop','projects','people','notes','help'].includes(panelMode)){
    const titles={research:['Small ideas. Curious consequences.','Grow the ingredients. Make the parts. See what happens.'],workshop:['Wren’s basement workshop','Each machine runs its own batch while you tend the farm.'],projects:['A town made together','Three shared projects open the way to the next chapter.'],people:['People worth knowing','Everybody arrived with a story. A few are still working out how to tell it.'],notes:['Things worth keeping','A field record of small breakthroughs and shared occasions.'],help:['Find your footing','A farm, a basement, and a town full of rather particular people.']};content=header(...titles[panelMode])+tabs(panelMode)+`<div class="panel-body">${({research:researchPanel,workshop:workshopPanel,projects:projectsPanel,people:peoplePanel,notes:notesPanel,help:helpPanel}[panelMode])()}</div>`;
  }else if(panelMode==='seeds')content=header('What shall we grow?','Choose a seed, then tap a tilled bed. Hold Plant to choose again.','THE SEED TIN')+`<div class="panel-body"><div class="grid">${Object.entries(CROPS).filter(([,c])=>c.phase<=state.phase).map(([id,c])=>`<div class="card crop-card">${sprite(c.sprite)}<div><h3>${c.name}</h3><p>${c.wet?'Creek beds only':'Garden beds'} · ${Math.ceil(E.growTime(state,id))}s</p><p>${state.seeds[id]||0} seeds in your tin</p><div class="card-footer"><button class="primary" data-action="seed" data-id="${id}" ${state.seeds[id]>0?'':'disabled'}>Plant ${c.short}</button></div></div></div>`).join('')}</div><div class="notice">Plant any land crop in the dry garden beds. Wirereed grows in the stitched creek beds on the right.</div><button class="secondary" data-action="visit-shop">Visit Pip’s seed counter</button></div>`;
  else if(panelMode==='bag')content=header('Mud on the outside. Wonders inside.',`${state.coins} coins · Crops and parts share the same pockets.`,'YOUR BAG')+`<div class="panel-body"><div class="bag-grid">${Object.entries(ITEMS).filter(([id])=>E.count(state,id)>0).map(([id,it])=>`<div class="bag-item"><span class="symbol">${it.icon}</span><div><strong>${it.name}</strong><small>${it.sell} coins each</small></div><b>${E.count(state,id)}</b></div>`).join('')||'<p class="empty">A little room for something new.</p>'}</div><h2 class="section-title">The seed tin</h2><div class="bag-grid">${Object.entries(CROPS).filter(([,c])=>c.phase<=state.phase).map(([id,c])=>`<div class="bag-item"><span class="symbol">${c.icon}</span><strong>${c.name}</strong><b>${state.seeds[id]||0}</b></div>`).join('')}</div><div class="card-footer"><button class="primary" data-open="seeds">Choose seeds</button><button class="secondary" data-action="visit-shop">Trade at Pip’s</button></div></div>`;
  else if(panelMode==='shop')content=shopPanel();
  else if(panelMode==='person')content=personPanel();
  else if(panelMode==='home')content=header('A place to put your boots','The porch swing has been expecting you.','WREN FARMHOUSE')+`<div class="panel-body"><div class="story-hero">${sprite(state.phase>1?8:0,true,'world')}</div><p class="prose">Your aunt’s note is still on the mantel.\n“Things grow here. You will too.”\n\nRest restores all your energy and starts a fresh day. Crops keep their progress; they never wither.</p><div class="card-footer"><button class="primary" data-action="sleep">Rest until morning</button><button class="secondary" data-action="to-cellar">Head downstairs</button></div></div>`;
  else if(panelMode==='diner')content=header('There’s room at table four',state.phase===3?'Breakfast served at a permanent six in the evening.':'Soup on the stove. Three cats out back.','BEA’S DINER')+`<div class="panel-body"><div class="portrait-head">${sprite(3,true)}<p class="prose">“First bowl of the day is on the house. Sit wherever the cat isn’t.”</p></div><div class="card-footer"><button class="primary" data-action="meal">Have a meal · ${state.mealDay!==state.day?'on the house':'12 coins'}</button><button class="secondary" data-person="bea">Talk with Bea</button></div><div class="divider"></div>${orderPanel()}</div>`;
  else if(panelMode==='settings')content=settingsPanel();
  else if(panelMode==='reset')content=header('Begin a new story?','This replaces the farm saved on this device. Export it first if you want to keep it.')+`<div class="panel-body"><div class="dialogue-actions"><button class="secondary" data-action="export">Export current farm</button><button class="danger" data-action="confirm-reset">Start a new farm</button><button class="secondary" data-open="settings">Keep this farm</button></div></div>`;
  else if(panelMode==='story')content=storyPanel();
  else if(panelMode==='ending')content=endingPanel();
  $('#panel-content').innerHTML=content;paintSprites();panel.scrollTop=scroll;
}
function researchPanel(){
  const g=E.gate(state);return `<div class="phase-tabs">${PHASES.map((name,i)=>`<button data-action="phase-view" data-id="${i+1}" class="${phaseView===i+1?'active':''}"><strong>Chapter ${['I','II','III'][i]}</strong>${name}</button>`).join('')}</div><div class="grid">${RESEARCH.filter(r=>r.phase===phaseView).map(r=>{const done=E.has(state,r.id),available=r.phase===state.phase&&r.requires.every(id=>E.has(state,id)),can=available&&E.affordable(state,r.cost);return `<article class="card ${done?'done':available?'':'locked'}">${done?'<span class="check-mark">✓</span>':''}<span class="eyebrow">${done?'IN THE WORLD':available?'ON THE WORKBENCH':'A LITTLE FURTHER ALONG'}</span><h3>${r.name}</h3><p>${r.desc}</p>${done?`<div class="notice">${r.effect}</div>`:cost(r.cost)}<div class="card-footer">${done?'<span class="small-note">Invented, mud and all.</span>':`<button class="primary" data-action="research" data-id="${r.id}" ${can?'':'disabled'}>Research</button><span class="small-note">${r.requires.filter(id=>!E.has(state,id)).map(id=>'Needs '+RESEARCH.find(n=>n.id===id).name).join(' · ')||r.effect}</span>`}</div></article>`;}).join('')}</div><div class="gate"><div><h3>${state.ending?'The quilt keeps growing':state.phase===3?'The impossible potluck':'Ready to turn the page?'}</h3><p>${g.research} / ${g.researchTotal} inventions · ${g.projects} / ${g.projectsTotal} town projects</p><div class="progress-track"><span style="width:${(g.research+g.projects)/9*100}%"></span></div></div><button class="primary" data-action="advance" ${g.ready&&!state.ending?'':'disabled'}>${state.phase===3?'Gather at the table':'Begin chapter '+(state.phase+1)}</button></div>`;
}
function workshopPanel(){return `<div class="notice">Ingredients go in at the start; finished parts go straight into your bag. Each machine processes one batch at a time. The farm keeps growing while you browse.</div>${RECIPES.map(r=>{const unlocked=E.has(state,r.research),job=state.jobs.find(j=>j.id===r.id);return `<div class="work-row">${sprite(r.sprite)}<div><h3>${r.name}</h3><p>${unlocked?Object.entries(r.output).map(([id,n])=>`${n} ${ITEMS[id].name}`).join(', ')+` per run · ${r.seconds/(E.has(state,'yesterday')?2:1)}s`:'Research '+RESEARCH.find(n=>n.id===r.research).name+' to build.'}</p>${unlocked?cost(r.input):''}${job?`<div class="inline-count" data-job="${r.id}">Working · ${Math.ceil(job.remaining/(E.has(state,'yesterday')?2:1))}s · ${job.batches} runs</div>`:''}</div><div class="work-actions">${unlocked&&!job?[1,5,'max'].map(n=>`<button class="${n===1?'primary':'secondary'}" data-action="craft" data-id="${r.id}" data-count="${n}" ${E.affordable(state,r.input,n==='max'?1:n)?'':'disabled'}>${n==='max'?'Max':`Make ×${n}`}</button>`).join(''):!unlocked?'<button class="secondary" data-open="research">Research</button>':''}</div></div>`;}).join('')}`;}
function orderPanel(){const o=E.currentOrder(state),p=PEOPLE.find(p=>p.id===o.person);return `<div class="card"><span class="eyebrow">TODAY’S ORDER · DAY ${state.day}</span><h3>${p.name} left a note</h3><p>“${o.line}”</p>${cost({[o.item]:o.count})}<div class="card-footer"><button class="primary" data-action="order" ${state.orderDone!==state.day&&E.count(state,o.item)>=o.count?'':'disabled'}>${state.orderDone===state.day?'Delivered ✓':'Deliver order'}</button><span class="small-note">${Math.round(o.pay*(E.has(state,'cooperative')?1.5:1))} coins + a little friendship</span></div></div>`;}
function projectsPanel(){return `${orderPanel()}<h2 class="section-title">Chapter ${state.phase}: shared projects</h2><div class="grid">${PROJECTS.filter(p=>p.phase===state.phase).map(p=>{const done=state.projects.includes(p.id),person=PEOPLE.find(n=>n.id===p.person);return `<div class="card ${done?'done':''}"><span class="eyebrow">WITH ${person.name.toUpperCase()} ${done?'· COMPLETE':''}</span><h3>${p.name}</h3><p>${done?p.after:p.text}</p>${done?'':cost(p.cost)}<div class="card-footer">${done?'<span class="small-note">A new stitch in the town.</span>':`<button class="primary" data-action="project" data-id="${p.id}" ${E.has(state,p.requires)&&E.affordable(state,p.cost)?'':'disabled'}>Build together</button><span class="small-note">${E.has(state,p.requires)?'Materials become a shared invention.':'Needs '+RESEARCH.find(r=>r.id===p.requires).name}</span>`}</div></div>`;}).join('')}</div><div class="notice">Visit the salvage yard in town for free copper, wood, stone, and bottle glass. Orson’s bank has creek clay. The piles replenish while you play.</div><button class="secondary" data-action="to-town">Walk into town</button>`;}
function peoplePanel(){return `<div class="grid">${PEOPLE.map(p=>`<button class="card person-card" data-person="${p.id}">${sprite(p.sprite)}<div><h3>${p.name}</h3><p>${p.role}</p><div class="hearts" aria-label="${Math.min(5,state.friendship[p.id]||0)} out of 5 friendship">${'●'.repeat(Math.min(5,state.friendship[p.id]||0))}${'○'.repeat(Math.max(0,5-(state.friendship[p.id]||0)))}</div></div></button>`).join('')}</div>`;}
function personPanel(){const p=PEOPLE.find(p=>p.id===personId),key=`${p.id}-${state.phase}`,choice=state.choices[key];return header(p.name,p.role,'A MOMENT WITH A NEIGHBOUR')+`<div class="panel-body"><div class="portrait-head">${sprite(p.sprite,true)}<div><p>${p.bio}</p><div class="hearts">${'●'.repeat(Math.min(5,state.friendship[p.id]||0))}${'○'.repeat(Math.max(0,5-(state.friendship[p.id]||0)))}</div></div></div><div class="quote">“${p.lines[state.phase-1][dialogueIndex%3]}”</div><div class="dialogue-actions"><button class="primary" data-action="talk">Stay a little longer</button><button class="secondary" data-action="gift" ${E.count(state,p.gift)>0&&state.gifts[p.id]!==state.day?'':'disabled'}>Give ${ITEMS[p.gift].name} (${E.count(state,p.gift)})</button></div><h2 class="section-title">${choice?'Something you said':'Leave a little of yourself here'}</h2>${choice?`<p class="notice">${esc(choice)}</p>`:`<div class="choice-list">${choicesFor(p.id).map((line,i)=>`<button data-action="choice" data-id="${i}">${line}</button>`).join('')}</div>`}<div class="divider"></div><button class="subtle" data-open="projects">See what you can make together</button></div>`;}
function choicesFor(id){return {mabel:['“I’d like to see the trick you most enjoy doing.”','“There’s always a place for you at our table.”'],jun:['“I noticed the part you made twice to get it right.”','“Leave the music in. It sounds like someone listening.”'],bea:['“I think table four might be my favourite place.”','“I can set the table if you sit down for once.”'],orson:['“Will you show me how Ellis tied that knot?”','“Let’s put both measurements in the book.”'],pip:['“Tell me where the next part came from.”','“Put the mender’s name on my receipt.”'],cleo:['“The minor characters are my favourite ones.”','“I’m listening. You can take your time.”']}[id];}
function notesPanel(){return `<div class="stat-row"><span><strong>${state.stats.harvested}</strong>Crops picked</span><span><strong>${state.research.length}</strong>Ideas made real</span><span><strong>${state.projects.length}</strong>Shared projects</span><span><strong>${state.day}</strong>Days in town</span></div>${state.ending?'<button class="primary" data-open="ending">Return to the potluck</button>':''}<article class="journal-entry"><span class="eyebrow">DAY 1</span><h3>${STORY[0].title}</h3><p>${STORY[0].body.replace(/\n/g,'<br>')}</p></article>${[...state.journal].reverse().map(j=>`<article class="journal-entry"><span class="eyebrow">DAY ${esc(j.day)}</span><h3>${esc(j.title)}</h3><p>${esc(j.body)}</p></article>`).join('')}`;}
function helpPanel(){return `<ol class="help-list"><li><strong>Make a little room.</strong> Choose Clear and tap a bramble, tree, or rock. Your farmer walks over and does the work.</li><li><strong>Grow something.</strong> Till a stitched bed, choose Plant and a seed, then Water. One watering lasts until harvest. Wirereed belongs in the creek beds to the right.</li><li><strong>Pick the gold sparkles.</strong> Choose Harvest, or use Explore on a ripe crop. Crops never wither. There is no punishment for taking your time.</li><li><strong>Go downstairs.</strong> The basement is beside the farmhouse. Research inventions with farm ingredients, then run batches on your machines.</li><li><strong>Walk into town.</strong> Buy seeds and sell produce at Pip’s, eat at Bea’s, talk to neighbours, and scavenge replenishing piles for free materials.</li><li><strong>Build the chapter.</strong> Each chapter has six inventions and three shared projects. Complete all nine, then turn the page in Research.</li></ol><div class="divider"></div><h2 class="section-title">Your hands, your pace</h2><p class="notice"><strong>Touch:</strong> tap to walk or work; drag the world to look around. The compass returns to your farmer. Tap Plant again to change seed.<br><strong>Keyboard:</strong> arrows / WASD to walk; 1–6 for tools; E / Space to work; B for bag; J for almanac; Escape to close.<br><strong>Rest:</strong> the farmhouse restores energy. Bea’s first meal each day is free. Time pauses when this tab is hidden. Saves stay on this device; export one from Settings to move it.</p><h2 class="section-title">A small, complete adventure</h2><p class="prose">Three chapters lead to one very peculiar potluck. Intended for about 2–3 hours of relaxed play, with room to stop, explore, and come back. You can keep tending the farm after the story ends.</p>`;}
function shopPanel(){return header(state.phase>1?'Pip’s peculiar exchange':'Seeds, supplies & second chances',state.phase>1?'Produce buys copper. Springs buy lunch. Every object comes with a little history.':'A place for anything that might yet be useful.','PIP’S COUNTER')+`<div class="panel-body"><span class="inline-count">◉ ${state.coins} coins in your pocket</span><h2 class="section-title">Seeds for the season</h2>${Object.entries(CROPS).filter(([,c])=>c.phase<=state.phase).map(([id,c])=>`<div class="shop-row">${sprite(c.sprite)}<div class="info"><h3>${c.name}</h3><p>${state.seeds[id]||0} in your tin · ${c.seed} coins each</p></div><button class="secondary" data-action="buy-seed" data-id="${id}" data-count="1" ${state.coins>=c.seed?'':'disabled'}>+1</button><button class="primary" data-action="buy-seed" data-id="${id}" data-count="5" ${state.coins>=c.seed*5?'':'disabled'}>5 for ${c.seed*5}</button></div>`).join('')}<h2 class="section-title">Parts with a past</h2>${['scrap','glass'].map(id=>`<div class="shop-row"><div class="info"><h3>${ITEMS[id].name}</h3><p>${ITEMS[id].buy} coins each · also free in the salvage yard</p></div><button class="secondary" data-action="buy-part" data-id="${id}" ${state.coins>=ITEMS[id].buy?'':'disabled'}>Buy one</button></div>`).join('')}<h2 class="section-title">Something to sell</h2>${Object.entries(ITEMS).filter(([id])=>E.count(state,id)>0).map(([id,it])=>`<div class="shop-row"><div class="info"><h3>${it.icon} ${it.name}</h3><p>${E.count(state,id)} in your bag · ${it.sell} coins each</p></div><button class="secondary" data-action="sell" data-id="${id}" data-count="1">Sell 1</button><button class="secondary" data-action="sell" data-id="${id}" data-count="5" ${E.count(state,id)>=5?'':'disabled'}>Sell 5</button></div>`).join('')||'<p class="empty">Bring something from the farm.</p>'}<div class="notice">Need a fresh start? Pip keeps a few cogsquash seeds for any farmer with empty pockets.</div><button class="secondary" data-action="seed-rescue">Ask about spare seeds</button></div>`;}
function settingsPanel(){return header('A few things in their right places','','SETTINGS & SAVES')+`<div class="panel-body"><div class="setting-row"><div><h3>Little sounds</h3><p>Soft notes for planting, harvesting, and inventions.</p></div><button class="secondary" data-action="sound" aria-pressed="${state.sound}">${state.sound?'Sound on':'Sound off'}</button></div><div class="setting-row"><div><h3>Your farm, in your pocket</h3><p>Auto-saved on this browser. Export a backup or import it on another device. An import replaces this device’s farm.</p></div><div class="buttons"><button class="secondary" data-action="export">Export save</button><button class="secondary" data-action="import">Import save</button></div></div><div class="setting-row"><div><h3>Begin again</h3><p>A fresh farm and a fresh pair of boots.</p></div><button class="secondary" data-open="reset">New farm</button></div><div class="setting-row"><div><h3>The field guide</h3><p>Controls, crops, and how chapters work.</p></div><button class="secondary" data-open="help">How to play</button></div><p class="small-note" style="margin-top:20px">Bumpkin Town · v1.0 · A game about ordinary people making peculiar things.</p></div>`;}
function storyPanel(){const story=STORY[state.phase-1];return header(story.title,'',`CHAPTER ${state.phase}`)+`<div class="panel-body"><div class="story-hero">${sprite(state.phase===1?0:state.phase===2?14:15,true,'world')}</div><p class="prose">${story.body}</p><div class="story-footer"><button class="primary" data-action="close">${state.phase===1?'Find my boots':'Let’s see what grows'}</button></div></div>`;}
function endingPanel(){return header('A place at the table','The Familiar Impossible','THE BUMPKIN TOWN POTLUCK')+`<div class="panel-body"><div class="story-hero">${sprite(15,true,'world')}</div><p class="prose">The table runs from the diner to the square. It bends once through yesterday, where somebody has already spilled the gravy.

Mabel produces a dove from an ordinary sleeve. Cleo recognises her own theme in the clink of Jun’s tiny train. Pip writes the mender’s name on a receipt. Orson measures the floating water, then checks the old knot.

Bea puts a spoon in the ketchup bottle.

You have changed what the town grows, what it trades, and what a neighbour can borrow. People now owe each other jars of evening, a little lift, and the occasional Tuesday. The boots by the doors are still muddy.

There is a chair left for you.

“Sit,” says Bea. “It’s going to get cold.”

For once, she is only approximately right.</p><div class="stat-row"><span><strong>${state.day}</strong>Days in town</span><span><strong>${state.research.length}</strong>Inventions</span><span><strong>${state.projects.length}</strong>Shared projects</span><span><strong>${Object.keys(state.choices).length}</strong>Conversations kept</span></div>${Object.entries(state.choices).length?`<h2 class="section-title">The things people remember</h2>${PEOPLE.filter(p=>Object.keys(state.choices).some(k=>k.startsWith(p.id+'-'))).map(p=>{const line=state.choices[`${p.id}-3`]||state.choices[`${p.id}-2`]||state.choices[`${p.id}-1`];return `<div class="journal-entry"><h3>${p.name}</h3><p>${esc(line)}</p></div>`;}).join('')}`:''}<div class="story-footer"><button class="primary" data-action="close">Tomorrow, there will be gardening</button></div></div>`;}
function meet(id){personId=id;dialogueIndex=0;if(state.talks[id]!==state.day){state.talks[id]=state.day;state.friendship[id]=Math.min(5,(state.friendship[id]||0)+1);save();}openPanel('person');}
function targetAction(target){
  const {kind,id}=target;if(kind==='travel')travel(id);
  else if(kind==='building'){if(id==='cellar')travel('cellar');else openPanel({house:'home',shop:'shop',diner:'diner',post:'projects'}[id]);}
  else if(kind==='person')meet(id);else if(kind==='scavenge')result(E.scavenge(state,id));else if(kind==='board')openPanel('projects');else if(kind==='research')openPanel('research');else if(kind==='machine')openPanel('workshop');
}
function doTile(x,y){const r=E.work(state,x,y,tool);result(r,{refresh:false});if(r.ok){world.burst(x,y,r.item?'+'+E.yieldFor(state):'',r.item?'#ffe6a2':'#efe1ba');if(r.item)sound('harvest');}}
function goTo(x,y,callback,adjacent=false){const path=E.findPath(state,x,y,adjacent);if(!path){notify('There’s something in the way. Try the path beside it.');return;}world.follow=true;route=path;pending=callback;if(!route.length){pending?.();pending=null;}}
let pointer=null;
canvas.addEventListener('pointerdown',ev=>{canvas.setPointerCapture(ev.pointerId);pointer={id:ev.pointerId,x:ev.clientX,y:ev.clientY,lastX:ev.clientX,lastY:ev.clientY,drag:false};});
canvas.addEventListener('pointermove',ev=>{const p=world.point(ev.clientX,ev.clientY);world.hover={x:Math.floor(p.x/E.SIZE),y:Math.floor(p.y/E.SIZE)};if(!pointer||pointer.id!==ev.pointerId)return;if(Math.hypot(ev.clientX-pointer.x,ev.clientY-pointer.y)>8)pointer.drag=true;if(pointer.drag){world.follow=false;world.camera.x-=(ev.clientX-pointer.lastX)/world.zoom;world.camera.y-=(ev.clientY-pointer.lastY)/world.zoom;world.camera.x=Math.max(120,Math.min(E.WIDTH*E.SIZE-100,world.camera.x));world.camera.y=Math.max(100,Math.min(E.HEIGHT*E.SIZE-100,world.camera.y));}pointer.lastX=ev.clientX;pointer.lastY=ev.clientY;});
canvas.addEventListener('pointercancel',()=>pointer=null);
canvas.addEventListener('pointerup',ev=>{if(!pointer||pointer.id!==ev.pointerId)return;const drag=pointer.drag;pointer=null;if(drag)return;const target=world.hit(ev.clientX,ev.clientY);if(target){targetAction(target);return;}const p=world.point(ev.clientX,ev.clientY),x=Math.floor(p.x/E.SIZE),y=Math.floor(p.y/E.SIZE);if(state.place!=='farm'){goTo(x,y,null);return;}const t=E.tileAt(state,x,y);if(!t)return;if(tool==='hand'&&!t.obstacle&&!t.crop){goTo(x,y,null);return;}goTo(x,y,()=>doTile(x,y),true);});
$('#recenter').addEventListener('click',()=>world.recenter(true));
$$('[data-tool]').forEach(b=>b.addEventListener('click',()=>setTool(b.dataset.tool)));
$$('[data-place]').forEach(b=>b.addEventListener('click',()=>travel(b.dataset.place)));
for(const [id,mode]of[['bag','bag'],['coins','bag'],['journal','research'],['mobile-journal','research'],['about','help'],['settings','settings']])$('#'+id).addEventListener('click',()=>openPanel(mode));
$('#quest-open').addEventListener('click',()=>{if(state.stats.cleared<3||state.stats.harvested<12||state.stats.planted<6)openPanel('help');else openPanel('research');});
panel.addEventListener('click',ev=>{if(ev.target===panel){const r=panel.getBoundingClientRect();if(ev.clientX<r.left||ev.clientX>r.right||ev.clientY<r.top||ev.clientY>r.bottom)closePanel();}});
panel.addEventListener('close',()=>{if(!panel.open)panelMode=null;});
$('#panel-content').addEventListener('click',ev=>{
  const b=ev.target.closest('button');if(!b||b.disabled)return;
  if(b.dataset.open){openPanel(b.dataset.open);return;}if(b.dataset.person){meet(b.dataset.person);return;}
  const action=b.dataset.action,id=b.dataset.id,n=+b.dataset.count;
  if(action==='close')closePanel();
  else if(action==='seed'){state.selectedSeed=id;closePanel();tool='seed';setTool('seed',false);save();}
  else if(action==='phase-view'){phaseView=+id;renderPanel();}
  else if(action==='research'){const r=E.unlock(state,id);result(r);if(r.ok)sound('success');}
  else if(action==='craft'){const r=RECIPES.find(r=>r.id===id),amount=b.dataset.count==='max'?Math.min(50,...Object.entries(r.input).map(([k,v])=>Math.floor(E.count(state,k)/v))):n;result(E.craft(state,id,amount));}
  else if(action==='project'){const r=E.finishProject(state,id);result(r);}
  else if(action==='advance'){const r=E.advance(state);result(r,{refresh:false});if(r.ok){phaseView=state.phase;openPanel(r.ending?'ending':'story');sound('success');}}
  else if(action==='buy-seed')result(E.buy(state,id,n,true));
  else if(action==='buy-part')result(E.buy(state,id,1,false));
  else if(action==='sell')result(E.sell(state,id,n));
  else if(action==='order')result(E.fulfillOrder(state));
  else if(action==='meal')result(E.meal(state));
  else if(action==='sleep'){result(E.sleep(state));closePanel();}
  else if(action==='visit-shop'){travel('town');openPanel('shop');}
  else if(action==='to-cellar')travel('cellar');
  else if(action==='to-town')travel('town');
  else if(action==='talk'){dialogueIndex++;renderPanel();}
  else if(action==='gift'){const p=PEOPLE.find(p=>p.id===personId);if(state.gifts[p.id]!==state.day&&E.spend(state,{[p.gift]:1})){state.gifts[p.id]=state.day;state.friendship[p.id]=Math.min(5,(state.friendship[p.id]||0)+1);result({ok:true,message:`${p.name} turns it over in their hands. “You remembered.”`});}}
  else if(action==='choice'){const key=`${personId}-${state.phase}`;if(!state.choices[key]){state.choices[key]=choicesFor(personId)[+id];state.friendship[personId]=Math.min(5,(state.friendship[personId]||0)+1);result({ok:true,message:'A small thing, remembered.'});}}
  else if(action==='sound'){state.sound=!state.sound;save();sound('success');renderPanel();}
  else if(action==='export'){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`bumpkin-town-day-${state.day}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notify('Your farm is packed up, boots included.');}
  else if(action==='import'){const input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.onchange=async()=>{const file=input.files?.[0];if(!file)return;if(file.size>2_000_000){notify('That file is too large to be a Bumpkin Town save.');return;}try{const raw=JSON.parse(await file.text());if(!E.validSave(raw))throw Error('invalid');state=raw;world.state=state;route=[];pending=null;world.recenter(true);save();updateHUD();closePanel();notify('Welcome back. Your boots are where you left them.');}catch{notify('That save could not be read. Your current farm is safe.');}};input.click();}
  else if(action==='confirm-reset'){state=E.newGame();world.state=state;route=[];pending=null;tool='hand';world.recenter(true);save();updateHUD();closePanel();setTool('hand');}
  else if(action==='seed-rescue'){if(state.coins<10&&(state.seeds.squash||0)<3){state.seeds.squash+=6;result({ok:true,message:'Pip hands you six seeds. “Gardening is a renewable proposition.”'});}else notify('“You’ve still got a little to work with. Come back if your pockets are empty.”');}
});
const held=new Set();let keyCooldown=0;
document.addEventListener('keydown',ev=>{if(panel.open)return;const k=ev.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright','w','a','s','d',' ','e'].includes(k)){ev.preventDefault();held.add(k);}if(ev.repeat)return;if('123456'.includes(k))setTool(['hand','clear','hoe','seed','water','harvest'][+k-1]);else if(k==='b')openPanel('bag');else if(k==='j')openPanel('research');else if(k==='e'||k===' '){const px=state.player.x*E.SIZE,py=state.player.y*E.SIZE;const targets=world.targets.map(t=>({...t,d:Math.hypot(t.x+t.w/2-px,t.y+t.h/2-py)})).sort((a,b)=>a.d-b.d);if(targets[0]?.d<125)targetAction(targets[0]);else{const p=world.hover&&Math.abs(world.hover.x-state.player.x)+Math.abs(world.hover.y-state.player.y)<3?world.hover:{x:Math.floor(state.player.x),y:Math.floor(state.player.y)+1};doTile(p.x,p.y);}}});
document.addEventListener('keyup',ev=>held.delete(ev.key.toLowerCase()));
window.addEventListener('blur',()=>held.clear());
document.addEventListener('visibilitychange',()=>{last=performance.now();held.clear();if(document.hidden)save();});
window.addEventListener('pagehide',save);
window.addEventListener('resize',()=>world.resize());
function move(dt){world.moving=false;if(panel.open)return;keyCooldown-=dt;const dx=Number(held.has('d')||held.has('arrowright'))-Number(held.has('a')||held.has('arrowleft')),dy=Number(held.has('s')||held.has('arrowdown'))-Number(held.has('w')||held.has('arrowup'));if((dx||dy)&&keyCooldown<=0){route=[];pending=null;const x=Math.floor(state.player.x)+(dx||0),y=Math.floor(state.player.y)+(dx?0:dy);if(E.walkable(state,x,y)){route=[[x,y]];world.follow=true;}keyCooldown=.15;}
  if(route.length){const [x,y]=route[0],tx=x+.5,ty=y+.5,dx=tx-state.player.x,dy=ty-state.player.y,d=Math.hypot(dx,dy),speed=4.8*dt;world.moving=true;if(d<=speed){state.player={x:tx,y:ty};route.shift();if(!route.length){const action=pending;pending=null;action?.();}}else{state.player.x+=dx/d*speed;state.player.y+=dy/d*speed;}}
}
function frame(time){const dt=Math.min(.1,(time-last)/1000||0);last=time;if(!document.hidden){move(dt);accum+=dt;saveAccum+=dt;if(accum>=.5){const events=E.tick(state,accum);accum=0;updateHUD();if(events.length){notify(events.at(-1).message);sound('success');if(panel.open)renderPanel();}for(const el of $$('[data-job]')){const job=state.jobs.find(j=>j.id===el.dataset.job);if(job)el.textContent=`Working · ${Math.ceil(job.remaining/(E.has(state,'yesterday')?2:1))}s · ${job.batches} runs`;}}if(saveAccum>=8){save();saveAccum=0;}world.render(reduced?0:time,dt);}requestAnimationFrame(frame);}
try{await world.load();$('#loading').classList.add('gone');world.recenter(true);updateHUD();save();requestAnimationFrame(frame);if(!state.tutorial){state.tutorial=true;notify('Welcome home. The golden squash are ready to pick.');save();}}
catch(err){$('#loading strong').textContent='The artwork didn’t finish loading.';$('#loading small').textContent='Refresh the page to unfold the town again.';console.error(err);}
